name: Deploy DEV/PRO
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Installing dependencies
        run: npm i
      - name: Building project
        run: npm run generate
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_PASS }}
          AWS_REGION: ${{ secrets.AWS_IAM_REGION }}
          SOURCE_DIR: 'dist'
