name: Deploy DEV/PRO
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Installing dependencies
        run: npm ci --foreground-script
      - name: Building project
        run: npm run generate
      - name: Configure AWS credentials from Websites account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secret-AWS_IAM_ROLE }}
          aws-region: ${{ secret-AWS_IAM_REGION }}
      - name: Sync files to the bucket and invalidate CloudFront cache
        run: |
          aws s3 sync dist s3://${{ secret.AWS_NAME }} --delete